# Generated by Django 5.0.2 on 2024-03-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
