# Generated by Django 5.0.4 on 2024-04-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_delete_person_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
